# Generated by Django 5.1.6 on 2025-03-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='publication_year',
        ),
    ]
